services:
  postgres:
    container_name: ms_pg-sql
    image: postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: huzaifa
      POSTGRES_PASSWORD: huzaifa
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4:latest
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVICE_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo:latest
    platform: linux/amd64
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=huzaifa
      - MONGO_INITDB_ROOT_PASSWORD=huzaifa
    networks:
      - microservices-net
    restart: unless-stopped


  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    platform: linux/amd64
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=huzaifa
      - ME_CONFIG_MONGODB_ADMINPASSWORD=huzaifa
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - microservices-net

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    platform: linux/amd64
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
